src/Entity/Offers.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table("Offers")
 * @ORM\Entity(repositoryClass="App\Repository\OffersRepository")
 */
class Offers
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $offer_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;


    /**
     * @ORM\Column(type="string", length=50)
     */

    private $price;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $time_location;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $options;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pictures;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nb_scooter_total;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nb_scooter_available;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOfferName(): ?string
    {
        return $this->offer_name;
    }

    public function setOfferName(string $offer_name): self
    {
        $this->offer_name = $offer_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription($description): ?string
    {
        return $this->description = $description;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getTimeLocation(): ?string
    {
        return $this->time_location;
    }

    public function setTimeLocation(string $time_location): self
    {
        $this->time_location = $time_location;

        return $this;
    }

    public function getOptions(): ?string
    {
        return $this->options;
    }

    public function setOptions(string $options): self
    {
        $this->options = $options;

        return $this;
    }

    public function getPictures(): ?string
    {
        return $this->pictures;
    }

    public function setPictures(string $pictures): self
    {
        $this->pictures = $pictures;

        return $this;
    }

    public function getNbScooterTotal(): ?string
    {
        return $this->nb_scooter_total;
    }

    public function setNbScooterTotal(string $nb_scooter_total): self
    {
        $this->nb_scooter_total = $nb_scooter_total;

        return $this;
    }

    public function getNbScooterAvailable(): ?string
    {
        return $this->nb_scooter_available;
    }

    public function setNbScooterAvailable(string $nb_scooter_available): self
    {
        $this->nb_scooter_available = $nb_scooter_available;

        return $this;
    }
}

src/Controller/FrontController.php
<?php
/**
 * Created by PhpStorm.
 * User: akim
 * Date: 14/02/2019
 * Time: 12:10
 */

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;


class FrontController extends AbstractController
{
    /**
     * @Route("/", name="home_page")
     */
    public function index()
    {
        return $this->render('front/home.html.twig');
    }
}

templates/front/home.html.twig
{% extends "layout.html.twig" %}


{% block body %}


    <section id="banner">
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <i class="icon fa-diamond"></i>
        {% else %}
            <i class="icon fa-diamond"></i>
        {% endif %}
        <h2>LocTaTrott'</h2>
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <p> Bonjour {{ app.user.firstname }}</p>
        {% endif %}
        <p>Trop de circulation sur la route? Marre d'attendre le métro? <br>Louez votre trottinette éléctrique avec
            LocTaTrot'</p>
        <ul class="actions">
            <li><a href="/offers" class="button big special">Louez votre Trottinette</a></li>
        </ul>

    </section>

    <!-- two -->
    <section class="wrapper special">
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-center">
                    Louer une trottinette selon vos besoins !
                </h2>
            </div>
            <br>
        </div>
        <div class="container">
            <div class="row">
                <div class="card-deck">
                    <div class="card" style="width: 18rem;">
                        <div class="img-card">
                            <img class="card-img-top" src="images/product/b1.jpg" alt="Card image cap">
                        </div>
                        <div class="card-body">
                            <div class="titre-card">
                                <h4>Votre choix de Trottinette</h4>
                            </div>
                            <div class="p-card">
                                <p class="card-text">
                                    Choisissez votre modèle de trottinettes,
                                    <strong>SILVER</strong>,
                                    <strong>GOLD</strong> ou
                                    <strong>PLATINIUM</strong>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="card" style="width: 18rem;">
                        <div class="img-card">
                            <img class="card-img-top" src="images/product/b2.jpg" alt="Card image cap">
                        </div>
                        <div class="card-body">
                            <div class="titre-card">
                                <h4>Pour combien de temps ?</h4>
                            </div>
                            <div class="p-card">
                                <p class="card-text">Partez sur
                                    <strong>3 mois de location</strong> en formule classique ou
                                    <strong>personnalisez votre offre</strong> en réduisant
                                    ou en augmentant la durée de location
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="card" style="width: 18rem;">
                        <div class="img-card">
                            <img class="card-img-top" src="images/product/b3.jpg" alt="Card image cap">
                        </div>
                        <div class="card-body">
                            <div class="titre-card">
                                <h4>Economisez du temps et de l'argent !</h4>
                            </div>
                            <div class="p-card">
                                <p class="card-text">Vous n'aurez plus à attendre le train , le métro ou le bus,
                                    déplacez vous plus facilement...
                                    Faites des <strong>économies</strong> en ne dépensant pas une fortune pour obtenir
                                    une trottinette électrique de grande qualité !
                                    On s'occupe de tout! Vous n'aurez qu'à payer un forfait chaque mois !
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- three -->
            <div class="row">

                <div class="col-xs-12">
                    <div class="inner">
                        <div class="major narrow">
                            <h2>Laissez vous séduire et bénéficiez de points de fidélité. </h2>
                        </div>
                        <iframe width="80%" height="315"
                                src="https://www.youtube.com/embed/qu3DKYWOQ9M"
                                frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen>
                        </iframe>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/front/offers-confirmation.html.twig
{% extends "layout.html.twig" %}

{% block content %}

    {#{{ dump(personnalize) }}
    {{ dump(offer) }}#}

    <!-- Header -->

    <!-- Content -->
    {% include 'component/_navbar.html.twig' %}
    <div>
        <h2 class="text-center ">Validez votre commande</h2>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4" >
                <div>
                    <h2>{{ offer.offerName }}</h2>
                </div>
                <div>
                    <img src="{{ asset('images/product/' ~ offer.pictures) }}" alt="">
                </div>
                <div>
                    <p class="text-justify">{{ offer.description }}</p>
                </div>
            </div>
            <div class="offset-2 col-md-6">
                <div>
                    <h2>Récapitulatif de votre commande</h2>
                </div>
                <br>
                <div>
                    <h3>Le durée de location</h3>
                    <span>{{ personnalize.location_duration }}</span>
                </div>
                <br>
                <div>
                    <h3>Vos options</h3>
                   <ul>
                       {% for key, options in personnalize.options  %}
                           <li>{{ key }}</li>
                       {% endfor %}
                   </ul>
                </div>
                <br>
                <div>
                    <h3>Votre tarif personnalisé</h3>
                    <span>{{  personnalize.total }}€/mois</span>
                </div>
                <div class="text-right">
                    <a class="btn-validation" href="{{ path('offers_validation') }}">Valider mon offre</a>
                </div>
            </div>
        </div>
    </div>
    {% include 'component/_footer.html.twig' %}
{% endblock %}

templates/front/offers.html.twig
{% extends "layout.html.twig" %}


{% block content %}

    <!-- Header -->
    {% include 'component/_navbar.html.twig' %}
    <!-- The 3 offers -->
        <div class="container">
            <div>
                <h2 class="my-3">Choisissez votre offre</h2>
            <div class="choice">
                <h2 class="my-3" style="background-color: #F9F8F7;">Nos offres</h2>
            </div>
            <div class="row">
                {% for offers in offers %}
                <div class="col-sm-4">
                    <div class="card">
                        <div style="height: 300px">
                            <img class="card-img-top"
                                 src="{{ asset('images/product/' ~ offers.pictures) }}"
                                 alt="Card image cap" style="width: 100%; height: 100%">
                        </div>
                        <h3 class="text-center mt-3">{{ offers.offername }}</h3>
                        <div class="card-body">
                            <div style="height: 300px">
                                <p class="card-text">{{ offers.description }}</p>
                                <p class="card-text">{{ offers.options }}</p>
                            </div>
                            <div>
                                <a href="#" class="button big alt">{{ offers.price }}</a>
                            <div class="options-offers">
                                <p class="car-text">{{ offers.options }}</p>
                            </div>
                            <div class="price-offers">
                                <span class="button big alt" >{{ offers.price }}</span>
                            </div>
                            <div class="time-loc-classic">
                                <p>Location pendant 3 mois</p>
                            </div>
                            <br><br>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <br><br>

            <br><br><br><br>
            <div>
                <h2 class="text-center" style="background-color: #F9F8F7;">
                    Selectionnez votre offre
                </h2>
            </div>
            <div id="personalizeOffer" class="form-group">
                {{ form(form) }}
            </div>
        </div>
    {% include 'component/_footer.html.twig' %}


{% endblock %}