src/Entity/Scooter.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * Scooter
 *
 * @ORM\Table(name="scooter")
 * @ORM\Entity(repositoryClass="App\Repository\ScooterRepository")
 */

class Scooter
{
    /**
     * @var int
     *
     * @ORM\Column(name="idscooter", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idscooter;

    /**
     * @var string|null
     *
     * @ORM\Column(name="scooter_name", type="string", length=45, nullable=true)
     */
    private $scooterName;
    /**
     * @var string|null
     *
     * @ORM\Column(name="scooter_model", type="string", length=45, nullable=true)
     */
    private $scooter_model;

    /**
     * @var int
     *
     * @ORM\Column(name="id_offer", type="integer", nullable=false)
     */

    private $id_offer;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="scooter_date_entry", type="date", nullable=true)
     */
    private $scooterDateEntry;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="scooter_date_next_maintenance", type="date", nullable=true)
     */
    private $scooterDateNextMaintenance;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="scooter_date_last_maintenance", type="date", nullable=true)
     */
    private $scooterDateLastMaintenance;

    /**
     * @var string|null
     *
     * @ORM\Column(name="scooter_statement", type="string", length=45, nullable=true)
     */
    private $scooterStatement;

    public function getIdscooter(): ?int
    {
        return $this->idscooter;
    }

    public function getScooterName(): ?string
    {
        return $this->scooterName;
    }

    public function setScooterName(?string $scooterName): self
    {
        $this->scooterName = $scooterName;

        return $this;
    }

    public function getScooterDateEntry(): ?\DateTimeInterface
    {
        return $this->scooterDateEntry;
    }

    public function setScooterDateEntry(?\DateTimeInterface $scooterDateEntry): self
    {
        $this->scooterDateEntry = $scooterDateEntry;

        return $this;
    }

    public function getScooterDateNextMaintenance(): ?\DateTimeInterface
    {
        return $this->scooterDateNextMaintenance;
    }

    public function setScooterDateNextMaintenance(?\DateTimeInterface $scooterDateNextMaintenance): self
    {
        $this->scooterDateNextMaintenance = $scooterDateNextMaintenance;

        return $this;
    }

    public function getScooterDateLastMaintenance(): ?\DateTimeInterface
    {
        return $this->scooterDateLastMaintenance;
    }

    public function setScooterDateLastMaintenance(?\DateTimeInterface $scooterDateLastMaintenance): self
    {
        $this->scooterDateLastMaintenance = $scooterDateLastMaintenance;

        return $this;
    }

    public function getScooterStatement(): ?string
    {
        return $this->scooterStatement;
    }

    public function setScooterStatement(?string $scooterStatement): self
    {
        $this->scooterStatement = $scooterStatement;

        return $this;
    }


    /**
     * Scooter constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->scooterDateEntry = new \DateTime();
    }

    /**
     * @param int $idscooter
     */
    public function setIdscooter(int $idscooter): void
    {
        $this->idscooter = $idscooter;
    }

    /**
     * @return string|null
     */
    public function getScooterModel(): ?string
    {
        return $this->scooter_model;
    }

    /**
     * @param string|null $scooter_model
     */
    public function setScooterModel(?string $scooter_model): void
    {
        $this->scooter_model = $scooter_model;
    }

    /**
     * @return mixed
     */
    public function getIdOffer()
    {
        return $this->id_offer;
    }

    /**
     * @param mixed $id_offer
     */
    public function setIdOffer($id_offer): void
    {
        $this->id_offer = $id_offer;
    }


}

src/Controller/ScooterController.php
<?php
/**
 * Created by PhpStorm.
 * User: Aks
 * Date: 15/02/2019
 * Time: 18:49
 */

namespace App\Controller;


use App\Entity\Scooter;
use App\Form\ScooterFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ScooterController extends AbstractController
{

    /**
     * @Route("/admin/scooter", name="scooter")
     */
    public function scooterIndex()
    {

        # Récupération du Repository
        $repository = $this->getDoctrine()
            ->getRepository(Scooter::class);


        $firstOffer = $repository->findFirstOffer();
        $secondOffer = $repository->findSecondOffer();
        $thirdOffer = $repository->findThirdOffer();

        // $secondOffer = $repository->findSecondOffer();

        # Rendu de la vue
        return $this->render('scooter/scooter.html.twig', [
            'firstOffer' => $firstOffer,
            'secondOffer'=> $secondOffer,
            'thirdOffer'=> $thirdOffer
        ]);
//        $repository = $this->getDoctrine()->getRepository(Scooter::class);
//        $scooter = $repository->findAll();
//
//        return $this->render('scooter/scooter.html.twig', [
//            'scooter' => $scooter,
//        ]);
    }

//    /**
//     * @Route("/scooter/tabStock", name="tab_stock")
//     * @param Scooter $scooter
//     * @return \Symfony\Component\HttpFoundation\JsonResponse
//     */
//    public function tabScooter(){
//
//        $repository = $this->getDoctrine()->getRepository(Scooter::class);
//
//        $scooter = $repository->findLastScooter();
//
//        return $this->json(['idScooter'=>$scooter["idScooter"]],200);
//    }



//    /**
//     * @Route("/scooter/tabStock", name="tab_stock")
//     */
//    public function tabScooter()
//    {
//        $scooter='';
//        # Récupération du Repository
//        $repository = $this->getDoctrine()
//            ->getRepository(Scooter::class);
//
//        if ($repository['id_offer'] === 0){
//            $scooter = $repository->findFirstOffer();
//         }
//        if ($repository['id_offer'] === 1){
//            $scooter = $repository->findSecondOffer();
//        }
//        if ($repository['id_offer'] === 2){
//            $scooter = $repository->findThirdOffer();
//        }
//
//
//        return $this->render('scooter/tabStock.html.twig',[
//            'scooter'=> $scooter
//        ]);
//
//    }


    /**
     * @Route("/admin/scooter/new", name="scooter_new", condition="request.isXmlHttpRequest()")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\JsonResponse|Response
     * @throws \Exception
     */
    public function newScooter(Request $request)
    {

        $scooter = new Scooter();


        $form = $this->createForm(ScooterFormType::class, $scooter, array(
            'action'=> $this->generateUrl($request->get('_route'))
        ))
            ->handleRequest($request);


        if($form->isSubmitted() && $form->isValid()) {


            $em = $this->getDoctrine()->getManager();
            $em->persist($scooter);
            $em->flush();
            return $this->json([
                'envoie'=>'ok',
                'id'=>$scooter->getIdscooter(),
                'name'=>$scooter->getScooterName(),
                'model'=>$scooter->getScooterModel(),
                'serialNumber'=>'50805',
                'date'=>$scooter->getScooterDateEntry(),
                'idoffer'=>$scooter->getIdOffer()
            ]);


        }


        return $this->render('scooter/form.html.twig', [
            'form' => $form->createView()
        ]);

    }

    /**
     * @Route("/admin/scooter/delete/{id}", name="scooter_delete")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\JsonResponse
     */
    public function deleteScooter(Request $request)
    {
        $idScooter = $request->get('idScooter');
        $scooter = $this->getDoctrine()
            ->getRepository(Scooter::class)
            ->find($idScooter);

        $em = $this->getDoctrine()->getManager();
        $em->remove($scooter);
        $em->flush();

        return $this->json(['delete'=>'ok','id'=>$request->get('idScooter')]);
    }

}

templates/scooter/form.html.twig
{{ form_start(form) }}
	{{ form_widget(form) }}
<div class="form-group row">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
        <button type="submit" id="btnForm' class="btn btn-primary" data-label="Enregistrer">
            Enregistrer
        </button>
    </div>
</div>
{{ form_end(form) }}

templates/scooter/scooter.html.twig
{% extends 'back/backHome.html.twig' %}

{% block body %}
<div class=container-fluid">
        <h3 style="text-align:center;">Gestion des Trotinettes</h3>
        <div class="row">
            <div class="col offset-5">
            <button class="button alt" data-toggle="modal" data-target="#exampleModal">
                <i class="fa fa-plus"></i> Ajouter une Trot
            </button>
            </div>
        </div><br>

{#{{ dump(firstOffer) }}#}



        <h2>OFFRE 1</h2>
        <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">N°</th>
                    <th scope="col">Marque</th>
                    <th scope="col">Model</th>
                    <th scope="col">Date arrivage</th>
                    <th scope="col">supprimer</th>
                </tr>
                </thead>
                <tbody id="list1">
                {% for scooter in firstOffer %}
                    <tr id="scooter-{{ scooter.idscooter }}" class="scooter-js">
                        <td>{{ scooter.idscooter }} </td>
                        <td>{{ scooter.scooterName }} </td>
                        <td>{{ scooter.scooterModel }} </td>
                        <td>{{ scooter.scooterDateEntry|date('d-m-Y') }}</td>
                        <td><a class="btn-js" href="javascript:void(0)" onclick="deleteScooter({{ scooter.idscooter }});"><i class="fas fa-trash-alt"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>


        <h2>OFFRE 2</h2>
        <table class="table table-bordered table-striped table-dark">
            <thead class="thead-light">
            <tr>
                <th scope="col">N°</th>
                <th scope="col">Marque</th>
                <th scope="col">Model</th>
                <th scope="col">Date arrivage</th>
                <th scope="col">supprimer</th>
            </tr>
            </thead>
            <tbody id="list2">
            {% for scooter in secondOffer %}
                <tr id="scooter-{{ scooter.idscooter }}" class="scooter-js">
                    <td>{{ scooter.idscooter }} </td>
                    <td>{{ scooter.scooterName }} </td>
                    <td>{{ scooter.scooterModel }} </td>
                    <td>{{ scooter.scooterDateEntry|date('d-m-Y') }}</td>
                    <td><a class="btn-js" href="javascript:void(0)" onclick="deleteScooter({{ scooter.idscooter }});"><i class="fas fa-trash-alt"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>



        <h2>OFFRE 3</h2>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">N°</th>
                <th scope="col">Marque</th>
                <th scope="col">Model</th>
                <th scope="col">Date arrivage</th>
                <th scope="col">supprimer</th>
            </tr>
            </thead>
            <tbody id="list3">
            {% for scooter in thirdOffer %}
                <tr id="scooter-{{ scooter.idscooter }}" class="scooter-js">
                    <td>{{ scooter.idscooter }} </td>
                    <td>{{ scooter.scooterName }} </td>
                    <td>{{ scooter.scooterModel }} </td>
                    <td>{{ scooter.scooterDateEntry|date('d-m-Y') }}</td>
                    <td><a class="btn-js" href="javascript:void(0)" onclick="deleteScooter({{ scooter.idscooter }});"><i class="fas fa-trash-alt"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>



</div>
    </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalTitle">Ajout d'une trotinette</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {#<script src="https://www.paypal.com/sdk/js?client-id=sb"></script>#}
    {#<script>paypal.Buttons().render('body');</script>#}
    <script>

    $('#exampleModal').on('shown.bs.modal', function () {
        var modal = $(this);
        $.ajax('{{ path('scooter_new') }}', {
            success: function(data) {
                modal.find('.modal-body').html(data);
            }
        });
    });
    {#$(document).on('hide.bs.modal', function () {#}
        {#var tab = $(this);#}
        {#$.ajax('{{ path('scooter_new') }}', {#}
            {#success: function(data) {#}
                {#console.log(data),#}
                {#tab.find('#list').html(data);#}
            {#}#}
        {#});#}
    {#});#}
    // $(document).on('hide.bs.modal', function (){
    // var element=document.querySelector('.scooter-js');
    // console.log(element);
    // $.ajax({
    //     type: 'POST',
    //     url: '/scooter/tab_stock/' + idScooter,
    //     data: {idScooter: idScooter},
    //     dataType: 'JSON',
    // })
    //     .done((data) => {
    //         console.log(data);
    //
    //             element.remove();
    //
    //     })
    // });


    function deleteScooter(idScooter) {

        $.ajax({
            type: 'POST',
            url: '/admin/scooter/delete/' + idScooter,
            data: {idScooter: idScooter},
            dataType: 'JSON',
        })
            .done((data) => {
                $("#scooter-"+idScooter).remove();
            });
    };

    $(document).on('submit', 'form', function(e){
        e.preventDefault();

        $form = $(e.target);
        $modal = $('#exampleModal');


        var $submitButton = $form.find(':submit');
        $submitButton.html('<i class="fas fa-spinner fa-pulse"></i>');
        $submitButton.prop('disabled', true);

        $form.ajaxSubmit({
            type: 'post',
            success: function(data) {
                console.log(data);
                if (data['envoie'] === 'ok') {
                    $("#exampleModal").modal('toggle');  // Ne fonctionne absolument pas
                   // $(".modal-backdrop").removeClass('show');
                    $(".modal-backdrop").remove();
                    {#$('#list'+data['idoffer']).append('<tr><td>'+data['id']+' </td><td> '+ data['name'] +' </td><td>'+ data['model'] +' </td><td>'+ data['SerialNumber'] +' </td><td>Today</td><td><a class="btn-js" href="javascript:void(0)" onclick="deleteScooter({{ scooter.idscooter }});"><i class="fas fa-trash-alt"></i></a></td></tr>');#}
                    $('#list'+data['idoffer']).append(`
                        <tr id="scooter-${data['id']}">
                            <td>${data['id']}</td>
                            <td>${data['name']}</td>
                            <td>${data['model']}</td>
                            <td>Today</td>
                            <td>
                                <a class="btn-js" href="javascript:void(0)" onclick="deleteScooter(${data['id']});">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                    `);

                } else {
                    $modal.find('.modal-body').html(data);
                }
            },
            error: function(jqXHR, status, error) {
                $submitButton.html(button.data('label'));
                $submitButton.prop('disabled', false);
            }
        });
    });
</script>

{% endblock  %}